const CHAPTER_TITLES: Record<string, Record<number, string>> = {
  'Genesis': {
    1: 'The Creation',
    2: 'The Garden of Eden',
    3: 'The Fall of Man',
    4: 'Cain and Abel',
    5: 'The Descendants of Adam',
    6: 'The Wickedness of Mankind',
    7: 'The Flood',
    8: 'The Waters Recede',
    9: 'God\'s Covenant with Noah',
    10: 'The Table of Nations',
    11: 'The Tower of Babel',
    12: 'The Call of Abram',
    15: 'God\'s Covenant with Abram',
    17: 'The Covenant of Circumcision',
    18: 'Three Visitors',
    19: 'The Destruction of Sodom',
    21: 'The Birth of Isaac',
    22: 'The Binding of Isaac',
    24: 'A Wife for Isaac',
    25: 'The Birth of Esau and Jacob',
    27: 'Jacob Steals the Blessing',
    28: 'Jacob\'s Dream at Bethel',
    32: 'Jacob Wrestles with God',
    37: 'Joseph\'s Dreams',
    39: 'Joseph in Potiphar\'s House',
    41: 'Pharaoh\'s Dreams',
    45: 'Joseph Reveals Himself',
    50: 'The Death of Joseph',
  },
  'Exodus': {
    1: 'The Israelites Oppressed',
    2: 'The Birth of Moses',
    3: 'The Burning Bush',
    7: 'The Plagues Begin',
    12: 'The Passover',
    14: 'Crossing the Red Sea',
    16: 'Manna and Quail',
    19: 'At Mount Sinai',
    20: 'The Ten Commandments',
    32: 'The Golden Calf',
  },
  'Leviticus': {
    16: 'The Day of Atonement',
    19: 'Laws of Holiness',
  },
  'Numbers': {
    6: 'The Nazirite Vow',
    13: 'The Twelve Spies',
    22: 'Balaam and the Donkey',
  },
  'Deuteronomy': {
    5: 'The Ten Commandments Repeated',
    6: 'The Greatest Commandment',
    28: 'Blessings and Curses',
    34: 'The Death of Moses',
  },
  'Joshua': {
    1: 'God Commissions Joshua',
    2: 'Rahab and the Spies',
    6: 'The Fall of Jericho',
    24: 'Choose This Day',
  },
  'Judges': {
    4: 'Deborah and Barak',
    6: 'The Call of Gideon',
    13: 'The Birth of Samson',
    16: 'Samson and Delilah',
  },
  'Ruth': {
    1: 'Naomi and Ruth',
    2: 'Ruth Meets Boaz',
    4: 'Boaz Redeems Ruth',
  },
  '1 Samuel': {
    1: 'The Birth of Samuel',
    3: 'The Lord Calls Samuel',
    8: 'Israel Asks for a King',
    16: 'David Anointed King',
    17: 'David and Goliath',
  },
  '2 Samuel': {
    5: 'David King Over All Israel',
    7: 'God\'s Covenant with David',
    11: 'David and Bathsheba',
  },
  '1 Kings': {
    3: 'Solomon\'s Wisdom',
    6: 'Solomon Builds the Temple',
    18: 'Elijah on Mount Carmel',
  },
  '2 Kings': {
    2: 'Elijah Taken Up to Heaven',
    5: 'Naaman Healed of Leprosy',
  },
  'Ezra': {
    1: 'The Proclamation of Cyrus',
    3: 'Rebuilding the Altar',
  },
  'Nehemiah': {
    1: 'Nehemiah\'s Prayer',
    2: 'Rebuilding the Wall',
    8: 'Ezra Reads the Law',
  },
  'Esther': {
    1: 'Queen Vashti Deposed',
    2: 'Esther Becomes Queen',
    4: 'For Such a Time as This',
  },
  'Job': {
    1: 'Job\'s Affliction',
    38: 'The Lord Speaks',
    42: 'Job\'s Restoration',
  },
  'Psalms': {
    1: 'The Way of the Righteous',
    2: 'The Reign of the Lord\'s Anointed',
    8: 'The Majesty of God',
    19: 'The Heavens Declare',
    22: 'My God, Why Have You Forsaken Me?',
    23: 'The Lord Is My Shepherd',
    24: 'The King of Glory',
    27: 'The Lord Is My Light',
    37: 'Trust in the Lord',
    40: 'A Song of Praise',
    46: 'God Is Our Refuge',
    51: 'A Prayer of Repentance',
    91: 'The Shelter of the Most High',
    100: 'A Psalm of Thanksgiving',
    103: 'Bless the Lord, O My Soul',
    119: 'The Word of God',
    121: 'The Lord Is Your Keeper',
    139: 'Search Me, O God',
    145: 'Great Is the Lord',
    150: 'Praise the Lord',
  },
  'Proverbs': {
    1: 'The Beginning of Knowledge',
    3: 'Trust in the Lord',
    31: 'The Excellent Wife',
  },
  'Ecclesiastes': {
    1: 'Everything Is Meaningless',
    3: 'A Time for Everything',
    12: 'Remember Your Creator',
  },
  'Song of Solomon': {
    1: 'The Bride and the Beloved',
  },
  'Isaiah': {
    6: 'Isaiah\'s Vision',
    7: 'The Sign of Immanuel',
    9: 'A Child Is Born',
    40: 'Comfort My People',
    53: 'The Suffering Servant',
    55: 'Come, Everyone Who Thirsts',
    61: 'The Year of the Lord\'s Favor',
  },
  'Jeremiah': {
    1: 'The Call of Jeremiah',
    29: 'A Letter to the Exiles',
    31: 'The New Covenant',
  },
  'Lamentations': {
    1: 'How Lonely Sits the City',
    3: 'Great Is Thy Faithfulness',
  },
  'Ezekiel': {
    1: 'The Vision of the Living Creatures',
    37: 'The Valley of Dry Bones',
  },
  'Daniel': {
    1: 'Daniel in Babylon',
    3: 'The Fiery Furnace',
    5: 'The Writing on the Wall',
    6: 'Daniel in the Lion\'s Den',
  },
  'Hosea': { 1: 'Hosea\'s Wife and Children' },
  'Joel': { 2: 'The Day of the Lord' },
  'Amos': { 5: 'Seek the Lord and Live' },
  'Jonah': { 1: 'Jonah Flees from the Lord', 2: 'Jonah\'s Prayer' },
  'Micah': { 5: 'A Ruler from Bethlehem', 6: 'What Does the Lord Require?' },
  'Habakkuk': { 1: 'Habakkuk\'s Complaint' },
  'Haggai': { 1: 'The Command to Rebuild the Temple' },
  'Zechariah': { 9: 'The Coming of Zion\'s King' },
  'Malachi': { 3: 'The Messenger of the Covenant' },
  'Matthew': {
    1: 'The Genealogy of Jesus',
    2: 'The Visit of the Wise Men',
    3: 'The Baptism of Jesus',
    4: 'The Temptation of Jesus',
    5: 'The Sermon on the Mount',
    6: 'Teaching About Prayer',
    7: 'Judging Others',
    8: 'Jesus Heals',
    10: 'The Twelve Apostles',
    13: 'Parables of the Kingdom',
    14: 'Jesus Walks on Water',
    16: 'Peter\'s Confession',
    17: 'The Transfiguration',
    19: 'Teaching About Divorce',
    21: 'The Triumphal Entry',
    22: 'The Greatest Commandment',
    24: 'Signs of the End',
    25: 'The Parable of the Talents',
    26: 'The Last Supper',
    27: 'The Crucifixion',
    28: 'The Resurrection',
  },
  'Mark': {
    1: 'The Beginning of the Gospel',
    4: 'Parables',
    5: 'Jesus Heals',
    10: 'The Rich Young Man',
    14: 'The Last Supper',
    15: 'The Crucifixion',
    16: 'The Resurrection',
  },
  'Luke': {
    1: 'The Birth of John Foretold',
    2: 'The Birth of Jesus',
    4: 'The Temptation of Jesus',
    10: 'The Good Samaritan',
    15: 'The Prodigal Son',
    22: 'The Last Supper',
    23: 'The Crucifixion',
    24: 'The Resurrection',
  },
  'John': {
    1: 'The Word Became Flesh',
    2: 'Water Into Wine',
    3: 'You Must Be Born Again',
    4: 'The Woman at the Well',
    6: 'The Bread of Life',
    8: 'The Light of the World',
    10: 'The Good Shepherd',
    11: 'The Raising of Lazarus',
    13: 'Jesus Washes the Disciples\' Feet',
    14: 'The Way, the Truth, and the Life',
    15: 'The Vine and the Branches',
    17: 'Jesus Prays for His Disciples',
    19: 'The Crucifixion',
    20: 'The Resurrection',
    21: 'Jesus and Peter',
  },
  'Acts': {
    1: 'The Ascension',
    2: 'The Day of Pentecost',
    3: 'Peter Heals a Lame Man',
    7: 'Stephen\'s Speech',
    9: 'The Conversion of Saul',
    10: 'Peter and Cornelius',
    13: 'Paul\'s First Missionary Journey',
    16: 'The Philippian Jailer',
    17: 'Paul in Athens',
    27: 'The Shipwreck',
  },
  'Romans': {
    1: 'The Righteous Shall Live by Faith',
    3: 'All Have Sinned',
    5: 'Peace with God',
    6: 'Dead to Sin, Alive in Christ',
    8: 'Life in the Spirit',
    12: 'A Living Sacrifice',
  },
  '1 Corinthians': {
    1: 'Divisions in the Church',
    12: 'One Body, Many Parts',
    13: 'The Greatest Is Love',
    15: 'The Resurrection of the Dead',
  },
  '2 Corinthians': {
    4: 'Treasure in Jars of Clay',
    5: 'The Ministry of Reconciliation',
    12: 'Paul\'s Thorn in the Flesh',
  },
  'Galatians': {
    2: 'Justified by Faith',
    5: 'The Fruit of the Spirit',
  },
  'Ephesians': {
    1: 'Spiritual Blessings in Christ',
    2: 'Saved by Grace',
    4: 'Unity in the Body',
    6: 'The Armor of God',
  },
  'Philippians': {
    1: 'To Live Is Christ',
    2: 'The Humility of Christ',
    3: 'Pressing Toward the Goal',
    4: 'Rejoice in the Lord',
  },
  'Colossians': {
    1: 'The Supremacy of Christ',
    3: 'Put On the New Self',
  },
  '1 Thessalonians': {
    4: 'The Coming of the Lord',
    5: 'The Day of the Lord',
  },
  '2 Thessalonians': {
    2: 'The Man of Lawlessness',
  },
  '1 Timothy': {
    2: 'Instructions on Worship',
    6: 'The Love of Money',
  },
  '2 Timothy': {
    2: 'A Good Soldier of Christ',
    3: 'All Scripture Is God-Breathed',
    4: 'Preach the Word',
  },
  'Titus': {
    2: 'Sound Doctrine',
    3: 'Saved by Grace',
  },
  'Philemon': {
    1: 'Paul\'s Appeal for Onesimus',
  },
  'Hebrews': {
    1: 'The Supremacy of the Son',
    4: 'A Sabbath Rest for God\'s People',
    11: 'By Faith',
    12: 'The Race Set Before Us',
  },
  'James': {
    1: 'Trials and Temptations',
    2: 'Faith and Works',
    3: 'Taming the Tongue',
  },
  '1 Peter': {
    1: 'A Living Hope',
    2: 'Living Stones',
  },
  '2 Peter': {
    1: 'Make Your Calling Sure',
    3: 'The Day of the Lord',
  },
  '1 John': {
    1: 'The Word of Life',
    3: 'Children of God',
    4: 'God Is Love',
  },
  'Revelation': {
    1: 'The Revelation of Jesus Christ',
    2: 'Letters to the Churches',
    4: 'The Throne in Heaven',
    5: 'The Scroll and the Lamb',
    12: 'The Woman and the Dragon',
    19: 'The Rider on the White Horse',
    20: 'The Thousand Years',
    21: 'A New Heaven and a New Earth',
    22: 'The River of Life',
  },
};

export function getChapterTitle(book: string, chapter: number): string | undefined {
  return CHAPTER_TITLES[book]?.[chapter];
}
